

CREATE SCHEMA "N"
    AUTHORIZATION postgres;

COMMENT ON SCHEMA "N"
    IS 'schema for nomenclatures';

GRANT ALL ON SCHEMA "N" TO PUBLIC;

GRANT ALL ON SCHEMA "N" TO postgres;


CREATE TABLE "N"."DistraintStatus"
(
    "Code" text COLLATE pg_catalog."default" NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "NameEn" text COLLATE pg_catalog."default",
    "Deactivated" boolean DEFAULT false,
    CONSTRAINT "DistraintStatus_pkey" PRIMARY KEY ("Code")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE "N"."DistraintStatus"
    OWNER to postgres;






CREATE TABLE "N"."PropertyType"
(
    "Code" text COLLATE pg_catalog."default" NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "NameEn" text COLLATE pg_catalog."default",
    "Deactivated" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PropertyType_pkey" PRIMARY KEY ("Code")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE "N"."PropertyType"
    OWNER to postgres;





CREATE TABLE "N"."RegiXSearchCriteriaType"
(
    "Code" text COLLATE pg_catalog."default" NOT NULL,
    "ElementName" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "DescriptionEn" text COLLATE pg_catalog."default",
    "Deactivated" boolean NOT NULL DEFAULT false,
    CONSTRAINT "RegiXSearchCriteriaType_pkey" PRIMARY KEY ("Code")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE "N"."RegiXSearchCriteriaType"
    OWNER to postgres;




CREATE TABLE "N"."UserRegisterType"
(
    "Code" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "NameEn" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Disabled" boolean NOT NULL DEFAULT false,
    "Sort" smallint NOT NULL,
    CONSTRAINT "UserRegisterType_pkey" PRIMARY KEY ("Code")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE "N"."UserRegisterType"
    OWNER to postgres;




CREATE TABLE "N"."UserType"
(
    "Code" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "NameEn" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Deactivated" boolean NOT NULL DEFAULT false,
    "Sort" smallint NOT NULL,
    CONSTRAINT "UserType_pkey" PRIMARY KEY ("Code")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE "N"."UserType"
    OWNER to postgres;




CREATE TABLE public."AspNetRoles"
(
    "Id" text COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default",
    "NormalizedName" character varying(256) COLLATE pg_catalog."default",
    "ConcurrencyStamp" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AspNetRoles"
    OWNER to postgres;

CREATE UNIQUE INDEX "RoleNameIndex"
    ON public."AspNetRoles" USING btree
    ("NormalizedName" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;




CREATE TABLE public."AspNetRoleClaims"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "RoleId" text COLLATE pg_catalog."default" NOT NULL,
    "ClaimType" text COLLATE pg_catalog."default",
    "ClaimValue" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES public."AspNetRoles" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AspNetRoleClaims"
    OWNER to postgres;

CREATE INDEX "IX_AspNetRoleClaims_RoleId"
    ON public."AspNetRoleClaims" USING btree
    ("RoleId" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;





CREATE TABLE public."AspNetUsers"
(
    "Id" text COLLATE pg_catalog."default" NOT NULL,
    "UserName" character varying(256) COLLATE pg_catalog."default",
    "NormalizedUserName" character varying(256) COLLATE pg_catalog."default",
    "Email" character varying(256) COLLATE pg_catalog."default",
    "NormalizedEmail" character varying(256) COLLATE pg_catalog."default",
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text COLLATE pg_catalog."default",
    "SecurityStamp" text COLLATE pg_catalog."default",
    "ConcurrencyStamp" text COLLATE pg_catalog."default",
    "PhoneNumber" text COLLATE pg_catalog."default",
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "Certificate" bytea,
    "Certificate_Thumbprint" text COLLATE pg_catalog."default",
    "Certificate_Name" text COLLATE pg_catalog."default",
    "Certificate_UniqueIdentifier" text COLLATE pg_catalog."default",
    "Deleted" boolean NOT NULL,
    "ConfirmedByAdmin" boolean NOT NULL,
    "UpdatedBy" text COLLATE pg_catalog."default",
    "UpdatedOn" date,
    "DeletedBy" text COLLATE pg_catalog."default",
    "DeletedOn" date,
    "ApprovedBy" text COLLATE pg_catalog."default",
    "ApprovedOn" date,
    "AuthType" character varying COLLATE pg_catalog."default" NOT NULL,
    "UserType" character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "ApprovedBy_AspNetUsers" FOREIGN KEY ("ApprovedBy")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "AspNetUser_Auth" FOREIGN KEY ("AuthType")
        REFERENCES "N"."UserRegisterType" ("Code") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "FK_DeletedBy_AspNetUsers" FOREIGN KEY ("DeletedBy")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "FK_UpdatedBy_AspNetUsers" FOREIGN KEY ("UpdatedBy")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "UserType_UserType" FOREIGN KEY ("UserType")
        REFERENCES "N"."UserType" ("Code") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AspNetUsers"
    OWNER to postgres;

CREATE INDEX "EmailIndex"
    ON public."AspNetUsers" USING btree
    ("NormalizedEmail" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE UNIQUE INDEX "UserNameIndex"
    ON public."AspNetUsers" USING btree
    ("NormalizedUserName" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX "fki_ApprovedBy_AspNetUsers"
    ON public."AspNetUsers" USING btree
    ("ApprovedBy" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX "fki_AspNetUser_Auth"
    ON public."AspNetUsers" USING btree
    ("AuthType" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX "fki_UserType_UserType"
    ON public."AspNetUsers" USING btree
    ("UserType" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;




CREATE TABLE public."AspNetUserClaims"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "ClaimType" text COLLATE pg_catalog."default",
    "ClaimValue" text COLLATE pg_catalog."default",
    CONSTRAINT "AspNetUserClaims_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AspNetUserClaims"
    OWNER to postgres;

CREATE INDEX "IX_AspNetUserClaims_UserId"
    ON public."AspNetUserClaims" USING btree
    ("UserId" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;



CREATE TABLE public."AspNetUserLogins"
(
    "LoginProvider" text COLLATE pg_catalog."default" NOT NULL,
    "ProviderKey" text COLLATE pg_catalog."default" NOT NULL,
    "ProviderDisplayName" text COLLATE pg_catalog."default",
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AspNetUserLogins"
    OWNER to postgres;

CREATE INDEX "IX_AspNetUserLogins_UserId"
    ON public."AspNetUserLogins" USING btree
    ("UserId" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;




CREATE TABLE public."AspNetUserRoles"
(
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "RoleId" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES public."AspNetRoles" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AspNetUserRoles"
    OWNER to postgres;

CREATE INDEX "IX_AspNetUserRoles_RoleId"
    ON public."AspNetUserRoles" USING btree
    ("RoleId" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;




CREATE TABLE public."AspNetUserTokens"
(
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "LoginProvider" text COLLATE pg_catalog."default" NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Value" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AspNetUserTokens"
    OWNER to postgres;




CREATE TABLE public."ActiveJWT"
(
    "JWT" text COLLATE pg_catalog."default" NOT NULL,
    "ExpDateUTC" date NOT NULL
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."ActiveJWT"
    OWNER to postgres;




CREATE SEQUENCE public."AircraftDebt_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public."AircraftDebt_Id_seq"
    OWNER TO postgres;




CREATE SEQUENCE public."AircraftRegistrationOperatorEntity_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public."AircraftRegistrationOperatorEntity_Id_seq"
    OWNER TO postgres;




CREATE SEQUENCE public."AircraftRegistrationOperatorPerson_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public."AircraftRegistrationOperatorPerson_Id_seq"
    OWNER TO postgres;




CREATE SEQUENCE public."AircraftRegistrationOwnerEntity_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public."AircraftRegistrationOwnerEntity_Id_seq"
    OWNER TO postgres;




CREATE SEQUENCE public."AircraftRegistrationOwnerPerson_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public."AircraftRegistrationOwnerPerson_Id_seq"
    OWNER TO postgres;





CREATE SEQUENCE public."AircraftRegistration_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public."AircraftRegistration_Id_seq"
    OWNER TO postgres;




CREATE SEQUENCE public."Aircraft_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public."Aircraft_Id_seq"
    OWNER TO postgres;




CREATE SEQUENCE public."Distraint_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public."Distraint_Id_seq"
    OWNER TO postgres;




CREATE SEQUENCE public."OtherProperty_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public."OtherProperty_Id_seq"
    OWNER TO postgres;




CREATE SEQUENCE public."RegiXReportToPropertyType_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 32767
    CACHE 1;

ALTER SEQUENCE public."RegiXReportToPropertyType_Id_seq"
    OWNER TO postgres;





CREATE SEQUENCE public."RegiXReport_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 32767
    CACHE 1;

ALTER SEQUENCE public."RegiXReport_Id_seq"
    OWNER TO postgres;





CREATE SEQUENCE public."RegiXRequest_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public."RegiXRequest_Id_seq"
    OWNER TO postgres;





CREATE SEQUENCE public."VehicleOwner_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public."VehicleOwner_Id_seq"
    OWNER TO postgres;




CREATE SEQUENCE public."VehicleUser_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public."VehicleUser_Id_seq"
    OWNER TO postgres;




CREATE SEQUENCE public."Vehicle_Id_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public."Vehicle_Id_seq"
    OWNER TO postgres;




CREATE TABLE public."Aircraft"
(
    "Id" integer NOT NULL DEFAULT nextval('"Aircraft_Id_seq"'::regclass),
    "ProducerName" text COLLATE pg_catalog."default",
    "ProducerNameEn" text COLLATE pg_catalog."default",
    "ProducerCountryCode" text COLLATE pg_catalog."default",
    "ProducerCountryName" text COLLATE pg_catalog."default",
    "AirCategoryCode" text COLLATE pg_catalog."default",
    "AirCategoryName" text COLLATE pg_catalog."default",
    "ICAO" text COLLATE pg_catalog."default",
    "MSNSerialNumber" text COLLATE pg_catalog."default",
    "ModelName" text COLLATE pg_catalog."default",
    "ModelNameEn" text COLLATE pg_catalog."default",
    CONSTRAINT "Aircraft_pkey" PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."Aircraft"
    OWNER to postgres;



CREATE TABLE public."AircraftDebt"
(
    "Id" integer NOT NULL DEFAULT nextval('"AircraftDebt_Id_seq"'::regclass),
    "AircraftId" integer NOT NULL,
    "InputDate" timestamp without time zone,
    "DebtTypeCode" integer,
    "DebtType" text COLLATE pg_catalog."default",
    "IsActive" boolean,
    "ApplicantIdentifier" text COLLATE pg_catalog."default",
    "ApplicantName" text COLLATE pg_catalog."default",
    "DocumentIncomingNumber" text COLLATE pg_catalog."default",
    "DocumentIncomingDate" timestamp without time zone,
    "DocumentExternalNumber" text COLLATE pg_catalog."default",
    "DocumentExternalDate" timestamp without time zone,
    "RepaymentDate" timestamp without time zone,
    "RepaymentDocumentIncomingNumber" text COLLATE pg_catalog."default",
    "RepaymentDocumentIncomingDate" timestamp without time zone,
    "RepaymentDocumentExternalNumber" text COLLATE pg_catalog."default",
    "RepaymentDocumentExternalDate" timestamp without time zone,
    "RepaymentNotes" text COLLATE pg_catalog."default",
    "Notes" text COLLATE pg_catalog."default",
    CONSTRAINT "AircraftDebt_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Aircraft_fkey" FOREIGN KEY ("AircraftId")
        REFERENCES public."Aircraft" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AircraftDebt"
    OWNER to postgres;




CREATE TABLE public."AircraftExtension"
(
    "AircraftId" integer NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "RequestId" bigint,
    "Deactivated" boolean NOT NULL DEFAULT false,
    CONSTRAINT "AircraftExtension_pkey" PRIMARY KEY ("AircraftId"),
    CONSTRAINT "Aircraft_fkey" FOREIGN KEY ("AircraftId")
        REFERENCES public."Aircraft" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AircraftExtension"
    OWNER to postgres;




CREATE TABLE public."AircraftRegistration"
(
    "Id" integer NOT NULL DEFAULT nextval('"AircraftRegistration_Id_seq"'::regclass),
    "AircraftId" integer NOT NULL,
    "ActNumber" integer,
    "RegistrationNumber" integer,
    "RegistrationDate" timestamp without time zone,
    "RegistrationMark" text COLLATE pg_catalog."default",
    "IsLastRegistration" boolean,
    "RegistrationStatusIsActive" boolean,
    "RegistrationStatusCode" integer,
    "RegistrationStatusName" text COLLATE pg_catalog."default",
    "RegistrationDocumentNumber" text COLLATE pg_catalog."default",
    "RegistrationDocumentDate" timestamp without time zone,
    "RegistrationDocumentDescription" text COLLATE pg_catalog."default",
    "DeregistrationDate" timestamp without time zone,
    "DeregistrationReason" text COLLATE pg_catalog."default",
    "DeregistrationDescription" text COLLATE pg_catalog."default",
    "DeregistrationCountryCode" text COLLATE pg_catalog."default",
    "DeregistrationCountryName" text COLLATE pg_catalog."default",
    "LeasingDocumentNumber" text COLLATE pg_catalog."default",
    "LeasingDocumentDate" timestamp without time zone,
    "LeasingEndDate" timestamp without time zone,
    "LeasingAgreement" text COLLATE pg_catalog."default",
    "LeasingLessorPersonIdentifier" text COLLATE pg_catalog."default",
    "LeasingLessorPersonNames" text COLLATE pg_catalog."default",
    "LeasingLessorEntityIdentifier" text COLLATE pg_catalog."default",
    "LeasingLessorEntityName" text COLLATE pg_catalog."default",
    CONSTRAINT "AircraftRegistration_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Aircraft_fkey" FOREIGN KEY ("AircraftId")
        REFERENCES public."Aircraft" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AircraftRegistration"
    OWNER to postgres;




CREATE TABLE public."AircraftRegistrationOperatorEntity"
(
    "Id" integer NOT NULL DEFAULT nextval('"AircraftRegistrationOperatorEntity_Id_seq"'::regclass),
    "RegistrationId" integer NOT NULL,
    "Identifier" text COLLATE pg_catalog."default",
    "Name" text COLLATE pg_catalog."default",
    CONSTRAINT "AircraftRegistrationOperatorEntity_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT registration_fkey FOREIGN KEY ("RegistrationId")
        REFERENCES public."AircraftRegistration" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AircraftRegistrationOperatorEntity"
    OWNER to postgres;




CREATE TABLE public."AircraftRegistrationOperatorPerson"
(
    "Id" integer NOT NULL DEFAULT nextval('"AircraftRegistrationOperatorPerson_Id_seq"'::regclass),
    "RegistrationId" integer NOT NULL,
    "Identifier" text COLLATE pg_catalog."default",
    "Names" text COLLATE pg_catalog."default",
    CONSTRAINT "AircraftRegistrationOperatorPerson_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Registration_fkey" FOREIGN KEY ("RegistrationId")
        REFERENCES public."AircraftRegistration" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AircraftRegistrationOperatorPerson"
    OWNER to postgres;





CREATE TABLE public."AircraftRegistrationOwnerEntity"
(
    "Id" integer NOT NULL DEFAULT nextval('"AircraftRegistrationOwnerEntity_Id_seq"'::regclass),
    "RegistrationId" integer NOT NULL,
    "Identifier" text COLLATE pg_catalog."default",
    "Name" text COLLATE pg_catalog."default",
    CONSTRAINT "AircraftRegistrationOwnerEntity_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Registration_fkey" FOREIGN KEY ("RegistrationId")
        REFERENCES public."AircraftRegistration" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AircraftRegistrationOwnerEntity"
    OWNER to postgres;





CREATE TABLE public."AircraftRegistrationOwnerPerson"
(
    "Id" integer NOT NULL DEFAULT nextval('"AircraftRegistrationOwnerPerson_Id_seq"'::regclass),
    "RegistrationId" integer NOT NULL,
    "Identifier" text COLLATE pg_catalog."default",
    "Names" text COLLATE pg_catalog."default",
    CONSTRAINT "AircraftRegistrationOwnerPerson_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Registration_fkey" FOREIGN KEY ("RegistrationId")
        REFERENCES public."AircraftRegistration" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."AircraftRegistrationOwnerPerson"
    OWNER to postgres;




CREATE TABLE public."OtherProperty"
(
    "Id" bigint NOT NULL DEFAULT nextval('"OtherProperty_Id_seq"'::regclass),
    "Identifier" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    CONSTRAINT "OtherProperty_pkey" PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."OtherProperty"
    OWNER to postgres;




CREATE TABLE public."Vehicle"
(
    "Id" bigint NOT NULL DEFAULT nextval('"Vehicle_Id_seq"'::regclass),
    "RegistrationNumber" text COLLATE pg_catalog."default" NOT NULL,
    "FirstRegistrationDate" timestamp without time zone,
    "VIN" text COLLATE pg_catalog."default" NOT NULL,
    "EngineNumber" text COLLATE pg_catalog."default",
    "VehicleType" text COLLATE pg_catalog."default",
    "Model" text COLLATE pg_catalog."default",
    "TypeApprovalNumber" text COLLATE pg_catalog."default",
    "ApprovalType" text COLLATE pg_catalog."default",
    "TradeDescription" text COLLATE pg_catalog."default",
    "Color" text COLLATE pg_catalog."default",
    "Category" text COLLATE pg_catalog."default",
    "OffRoadSymbols" text COLLATE pg_catalog."default",
    "MassG" text COLLATE pg_catalog."default",
    "MassF1" text COLLATE pg_catalog."default",
    "MassF2" text COLLATE pg_catalog."default",
    "MassF3" text COLLATE pg_catalog."default",
    "VehicleNumOfAxles " text COLLATE pg_catalog."default",
    "VehicleMassO1" text COLLATE pg_catalog."default",
    "VehicleMassO2" text COLLATE pg_catalog."default",
    "Capacity" text COLLATE pg_catalog."default",
    "MaxPower" text COLLATE pg_catalog."default",
    "Fuel" text COLLATE pg_catalog."default",
    "EnvironmentalCategory" text COLLATE pg_catalog."default",
    "VehicleDocumentNumber" text COLLATE pg_catalog."default",
    "VehicleDocumentDate" timestamp without time zone,
    CONSTRAINT "Vehicle_pkey" PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."Vehicle"
    OWNER to postgres;




CREATE TABLE public."VehicleExtension"
(
    "VehicleId" bigint NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "RequestId" bigint,
    "Deactivated" boolean NOT NULL DEFAULT false,
    CONSTRAINT "VehicleExtension_pkey" PRIMARY KEY ("VehicleId"),
    CONSTRAINT "Vehicle_fkey" FOREIGN KEY ("VehicleId")
        REFERENCES public."Vehicle" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."VehicleExtension"
    OWNER to postgres;




CREATE TABLE public."VehicleOwner"
(
    "Id" bigint NOT NULL DEFAULT nextval('"VehicleOwner_Id_seq"'::regclass),
    "VehicleId" bigint NOT NULL,
    "BulgarianCitizenPin" text COLLATE pg_catalog."default",
    "BulgarianCitizenFirstName" text COLLATE pg_catalog."default",
    "BulgarianCitizenMiddleName" text COLLATE pg_catalog."default",
    "BulgarianCitizenLastName" text COLLATE pg_catalog."default",
    "ForeignCitizenPin" text COLLATE pg_catalog."default",
    "ForeignCitizenPn" text COLLATE pg_catalog."default",
    "ForeignCitizenNamesCyrillic" text COLLATE pg_catalog."default",
    "ForeignCitizenNamesLatin" text COLLATE pg_catalog."default",
    "ForeignCitizenNationality" text COLLATE pg_catalog."default",
    "CompanyId" text COLLATE pg_catalog."default",
    "CompanyName" text COLLATE pg_catalog."default",
    "CompanyNameLatin" text COLLATE pg_catalog."default",
    CONSTRAINT "VehicleOwner_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "vehicle+fkey" FOREIGN KEY ("VehicleId")
        REFERENCES public."Vehicle" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."VehicleOwner"
    OWNER to postgres;




CREATE TABLE public."VehicleUser"
(
    "Id" bigint NOT NULL DEFAULT nextval('"VehicleUser_Id_seq"'::regclass),
    "VehicleId" bigint NOT NULL,
    "BulgarianCitizenPin" text COLLATE pg_catalog."default",
    "BulgarianCitizenFirstName" text COLLATE pg_catalog."default",
    "BulgarianCitizenMiddleName" text COLLATE pg_catalog."default",
    "BulgarianCitizenLastName" text COLLATE pg_catalog."default",
    "ForeignCitizenPin" text COLLATE pg_catalog."default",
    "ForeignCitizenPn" text COLLATE pg_catalog."default",
    "ForeignCitizenNamesCyrillic" text COLLATE pg_catalog."default",
    "ForeignCitizenNamesLatin" text COLLATE pg_catalog."default",
    "ForeignCitizenNationality" text COLLATE pg_catalog."default",
    "CompanyId" text COLLATE pg_catalog."default",
    "CompanyName" text COLLATE pg_catalog."default",
    "CompanyNameLatin" text COLLATE pg_catalog."default",
    CONSTRAINT "VehicleUser_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Vehicle_fkey" FOREIGN KEY ("VehicleId")
        REFERENCES public."Vehicle" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."VehicleUser"
    OWNER to postgres;




CREATE TABLE public."UserLogs"
(
    "ActionName" character varying(100) COLLATE pg_catalog."default",
    "Controller" character varying(100) COLLATE pg_catalog."default",
    "Data" text COLLATE pg_catalog."default",
    "Id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Message" text COLLATE pg_catalog."default",
    "RequestMethod" character varying(50) COLLATE pg_catalog."default",
    "Result" character varying(500) COLLATE pg_catalog."default",
    "ServerTimeUtc" timestamp without time zone NOT NULL,
    "UserId" character varying(450) COLLATE pg_catalog."default",
    "Ip" character varying(128) COLLATE pg_catalog."default",
    "Duration" bigint,
    "ResponseStatusCode" bigint,
    CONSTRAINT "UserLogs_pkey" PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."UserLogs"
    OWNER to postgres;




CREATE TABLE public."RegiXReport"
(
    "Id" smallint NOT NULL DEFAULT nextval('"RegiXReport_Id_seq"'::regclass),
    "ProviderName" text COLLATE pg_catalog."default",
    "RegisterName" text COLLATE pg_catalog."default",
    "ReportName" text COLLATE pg_catalog."default" NOT NULL,
    "AdapterSubdirectory" text COLLATE pg_catalog."default" NOT NULL,
    "OperationName" text COLLATE pg_catalog."default",
    "RequestXsd" text COLLATE pg_catalog."default",
    "ResponseXsd" text COLLATE pg_catalog."default",
    "Operation" text COLLATE pg_catalog."default",
    "IsDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "RegiXReport_pkey" PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."RegiXReport"
    OWNER to postgres;

COMMENT ON TABLE public."RegiXReport"
    IS 'Конфигурация на справките от RegiX';





CREATE TABLE public."RegiXReportToPropertyType"
(
    "Id" smallint NOT NULL DEFAULT nextval('"RegiXReportToPropertyType_Id_seq"'::regclass),
    "RegiXReportId" smallint NOT NULL,
    "RegiXSearchCriteriaTypeCode" text COLLATE pg_catalog."default" NOT NULL,
    "PropertyTypeCode" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "RegiXReportToPropertyType_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "PropertyType_fkey" FOREIGN KEY ("PropertyTypeCode")
        REFERENCES "N"."PropertyType" ("Code") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "ReportId_fkey" FOREIGN KEY ("RegiXReportId")
        REFERENCES public."RegiXReport" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "SearchCriteria_fkey" FOREIGN KEY ("RegiXSearchCriteriaTypeCode")
        REFERENCES "N"."RegiXSearchCriteriaType" ("Code") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."RegiXReportToPropertyType"
    OWNER to postgres;




CREATE TABLE public."RegiXRequest"
(
    "Id" bigint NOT NULL DEFAULT nextval('"RegiXRequest_Id_seq"'::regclass),
    "UserId" text COLLATE pg_catalog."default",
    "RegiXReportId" smallint NOT NULL,
    "Argument" text COLLATE pg_catalog."default" NOT NULL,
    "CreatedAtUtc" timestamp without time zone,
    "AnsweredAtUtc" timestamp without time zone,
    "Errors" text COLLATE pg_catalog."default",
    CONSTRAINT "RegiXRequest_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Report_fkey" FOREIGN KEY ("RegiXReportId")
        REFERENCES public."RegiXReport" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "User_fkey" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."RegiXRequest"
    OWNER to postgres;





CREATE TABLE public."RegiXResponse"
(
    "RequestId" bigint NOT NULL,
    "RawContent" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "RegiXResponse_pkey" PRIMARY KEY ("RequestId"),
    CONSTRAINT "RegiXResponse_fkey" FOREIGN KEY ("RequestId")
        REFERENCES public."RegiXRequest" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."RegiXResponse"
    OWNER to postgres;





CREATE TABLE public."Person"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FirstName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "MiddleName" character varying(50) COLLATE pg_catalog."default",
    "LastName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "UserId" character varying(450) COLLATE pg_catalog."default",
    "CreatedBy" character varying(450) COLLATE pg_catalog."default",
    "CreatedOn" date NOT NULL,
    "UpdatedBy" character varying(450) COLLATE pg_catalog."default",
    "UpdatedOn" timestamp without time zone,
    "Deleted" boolean NOT NULL DEFAULT false,
    "DeletedBy" character varying(450) COLLATE pg_catalog."default",
    "DeletedOn" timestamp without time zone,
    CONSTRAINT "Person_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "CreatedBy_Person" FOREIGN KEY ("CreatedBy")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "DeletedBy_Person" FOREIGN KEY ("DeletedBy")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "UpdatedBy_Person" FOREIGN KEY ("UpdatedBy")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."Person"
    OWNER to postgres;

CREATE INDEX "fki_CreatedOn_Person"
    ON public."Person" USING btree
    ("CreatedBy" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX "fki_DeletedBy_Person"
    ON public."Person" USING btree
    ("DeletedBy" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX "fki_EditedBy_Person"
    ON public."Person" USING btree
    ("UpdatedBy" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;



CREATE TABLE public."Distraint"
(
    "Id" bigint NOT NULL DEFAULT nextval('"Distraint_Id_seq"'::regclass),
    "PropertyIdVehicle" bigint,
    "PropertyIdAircraft" integer,
    "PropertyIdVessel" integer,
    "PropertyIdAgriForMachinery" bigint,
    "PropertyIdRealEstate" bigint,
    "PropertyIdOtherProperty" bigint,
    "StatusCode" text COLLATE pg_catalog."default",
    "ApplyDate" timestamp without time zone,
    "InFavourOf" text COLLATE pg_catalog."default",
    "SuitNumber" text COLLATE pg_catalog."default",
    "Debtor" text COLLATE pg_catalog."default",
    "CancelDate" timestamp without time zone,
    "CreatedOn" timestamp without time zone NOT NULL,
    "CreatedBy" text COLLATE pg_catalog."default",
    "UpdatedOn" timestamp without time zone,
    "UpdatedBy" text COLLATE pg_catalog."default",
    "Deactivated" boolean NOT NULL DEFAULT false,
    "PropertyTypeCode" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Distraint_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Aircraft_fkey" FOREIGN KEY ("PropertyIdAircraft")
        REFERENCES public."Aircraft" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "CreatedBy_fkey" FOREIGN KEY ("CreatedBy")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "OtherProperty_fkey" FOREIGN KEY ("PropertyIdOtherProperty")
        REFERENCES public."OtherProperty" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "PropertyType_fkey" FOREIGN KEY ("PropertyTypeCode")
        REFERENCES "N"."PropertyType" ("Code") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "Status_fkey" FOREIGN KEY ("StatusCode")
        REFERENCES "N"."DistraintStatus" ("Code") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "UpdatedBy_fkey" FOREIGN KEY ("UpdatedBy")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "Vehicle_fkey" FOREIGN KEY ("PropertyIdVehicle")
        REFERENCES public."Vehicle" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."Distraint"
    OWNER to postgres;

-- 23.10.2020 Angel
alter table "N"."UserRegisterType"
add "IsPublic" boolean not null default true;

update "N"."UserRegisterType"
set "IsPublic"  = false
where "Code" = 'CHSI';
-- end

