using System;
using System.Collections.Generic;
using System.Text;

namespace EDeliveryServiceReference
{
    using System.Collections.Generic;
    using System.Linq;
    using System.ServiceModel.Channels;
    using System.ServiceModel.Description;
    using WcfCoreMtomEncoder;

    public partial class EDeliveryIntegrationServiceClient // DocumentWebServiceClient is generated by the WCF
    {
         public void ConfigureEndpoint(ServiceEndpoint serviceEndpoint
             //, ClientCredentials clientCredentials
             )
        {
            var messageEncodingBindingElementType = typeof(MessageEncodingBindingElement);
            var elements = serviceEndpoint.Binding.CreateBindingElements();

            IEnumerable<BindingElement> elementsWithoutEncodingElement = elements.Where(item => !messageEncodingBindingElementType.IsAssignableFrom(item.GetType()));
            var existingEncodingElement = (MessageEncodingBindingElement)elements.Where(item => messageEncodingBindingElementType.IsAssignableFrom(item.GetType())).First();

            var newEncodingElement = new MtomMessageEncoderBindingElement(existingEncodingElement);

            // Encoding is before transport, so we prepend the MTOM message encoding binding element
            // https://docs.microsoft.com/en-us/dotnet/framework/wcf/extending/custom-bindings
            var cb = new CustomBinding(elementsWithoutEncodingElement.Prepend(newEncodingElement));
            serviceEndpoint.Binding = cb;
        }
    }
}
