using System;

namespace NRZ.RegiX.Client.ResponseModels
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse", IsNullable = false)]
    public partial class AircraftsResponse : BaseResponse
    {

        private Aircraft[] aircraftField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Aircraft")]
        public Aircraft[] Aircraft
        {
            get
            {
                return this.aircraftField;
            }
            set
            {
                this.aircraftField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class Aircraft
    {

        private Producer producerField;

        private AirCategory airCategoryField;

        private string iCAOField;

        private string bGModelNameField;

        private string eNModelNameField;

        private string mSNSerialNumberField;

        private Registrations registrationsField;

        private Debts debtsField;

        /// <remarks/>
        public Producer Producer
        {
            get
            {
                return this.producerField;
            }
            set
            {
                this.producerField = value;
            }
        }

        /// <remarks/>
        public AirCategory AirCategory
        {
            get
            {
                return this.airCategoryField;
            }
            set
            {
                this.airCategoryField = value;
            }
        }

        /// <remarks/>
        public string ICAO
        {
            get
            {
                return this.iCAOField;
            }
            set
            {
                this.iCAOField = value;
            }
        }

        /// <remarks/>
        public string BGModelName
        {
            get
            {
                return this.bGModelNameField;
            }
            set
            {
                this.bGModelNameField = value;
            }
        }

        /// <remarks/>
        public string ENModelName
        {
            get
            {
                return this.eNModelNameField;
            }
            set
            {
                this.eNModelNameField = value;
            }
        }

        /// <remarks/>
        public string MSNSerialNumber
        {
            get
            {
                return this.mSNSerialNumberField;
            }
            set
            {
                this.mSNSerialNumberField = value;
            }
        }

        /// <remarks/>
        public Registrations Registrations
        {
            get
            {
                return this.registrationsField;
            }
            set
            {
                this.registrationsField = value;
            }
        }

        /// <remarks/>
        public Debts Debts
        {
            get
            {
                return this.debtsField;
            }
            set
            {
                this.debtsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class Producer
    {

        private string nameField;

        private string nameEnField;

        private string countryCodeField;

        private string countryNameField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string NameEn
        {
            get
            {
                return this.nameEnField;
            }
            set
            {
                this.nameEnField = value;
            }
        }

        /// <remarks/>
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        public string CountryName
        {
            get
            {
                return this.countryNameField;
            }
            set
            {
                this.countryNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class Repayment
    {

        private System.DateTime repaymentDateField;

        private bool repaymentDateFieldSpecified;

        private DocumentType repaymentDocumentField;

        private string notesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime RepaymentDate
        {
            get
            {
                return this.repaymentDateField;
            }
            set
            {
                this.repaymentDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RepaymentDateSpecified
        {
            get
            {
                return this.repaymentDateFieldSpecified;
            }
            set
            {
                this.repaymentDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public DocumentType RepaymentDocument
        {
            get
            {
                return this.repaymentDocumentField;
            }
            set
            {
                this.repaymentDocumentField = value;
            }
        }

        /// <remarks/>
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class DocumentType
    {

        private string incomingNumberField;

        private System.DateTime incomingDateField;

        private bool incomingDateFieldSpecified;

        private string externalNumberField;

        private System.DateTime externalDateField;

        private bool externalDateFieldSpecified;

        /// <remarks/>
        public string IncomingNumber
        {
            get
            {
                return this.incomingNumberField;
            }
            set
            {
                this.incomingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime IncomingDate
        {
            get
            {
                return this.incomingDateField;
            }
            set
            {
                this.incomingDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncomingDateSpecified
        {
            get
            {
                return this.incomingDateFieldSpecified;
            }
            set
            {
                this.incomingDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ExternalNumber
        {
            get
            {
                return this.externalNumberField;
            }
            set
            {
                this.externalNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime ExternalDate
        {
            get
            {
                return this.externalDateField;
            }
            set
            {
                this.externalDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExternalDateSpecified
        {
            get
            {
                return this.externalDateFieldSpecified;
            }
            set
            {
                this.externalDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class AircraftDebts
    {

        private System.DateTime inputDateField;

        private bool inputDateFieldSpecified;

        private int debtTypeCodeField;

        private bool debtTypeCodeFieldSpecified;

        private string debtTypeField;

        private bool isActiveField;

        private bool isActiveFieldSpecified;

        private Entity applicantField;

        private DocumentType documentField;

        private Repayment repaymentField;

        private string notesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime InputDate
        {
            get
            {
                return this.inputDateField;
            }
            set
            {
                this.inputDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InputDateSpecified
        {
            get
            {
                return this.inputDateFieldSpecified;
            }
            set
            {
                this.inputDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int DebtTypeCode
        {
            get
            {
                return this.debtTypeCodeField;
            }
            set
            {
                this.debtTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DebtTypeCodeSpecified
        {
            get
            {
                return this.debtTypeCodeFieldSpecified;
            }
            set
            {
                this.debtTypeCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string DebtType
        {
            get
            {
                return this.debtTypeField;
            }
            set
            {
                this.debtTypeField = value;
            }
        }

        /// <remarks/>
        public bool IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsActiveSpecified
        {
            get
            {
                return this.isActiveFieldSpecified;
            }
            set
            {
                this.isActiveFieldSpecified = value;
            }
        }

        /// <remarks/>
        public Entity Applicant
        {
            get
            {
                return this.applicantField;
            }
            set
            {
                this.applicantField = value;
            }
        }

        /// <remarks/>
        public DocumentType Document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }

        /// <remarks/>
        public Repayment Repayment
        {
            get
            {
                return this.repaymentField;
            }
            set
            {
                this.repaymentField = value;
            }
        }

        /// <remarks/>
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class Entity
    {

        private string identifierField;

        private string nameField;

        /// <remarks/>
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class Debts
    {

        private AircraftDebts[] debtField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Debt")]
        public AircraftDebts[] Debt
        {
            get
            {
                return this.debtField;
            }
            set
            {
                this.debtField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class EntitiesList
    {

        private Entity[] entityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Entity")]
        public Entity[] Entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class PersonList
    {

        private Person[] personField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Person")]
        public Person[] Person
        {
            get
            {
                return this.personField;
            }
            set
            {
                this.personField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class Person
    {

        private string identifierField;

        private string namesField;

        /// <remarks/>
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        public string Names
        {
            get
            {
                return this.namesField;
            }
            set
            {
                this.namesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class PersonEntitiesLists
    {

        private PersonList personListField;

        private EntitiesList entitiesListField;

        /// <remarks/>
        public PersonList PersonList
        {
            get
            {
                return this.personListField;
            }
            set
            {
                this.personListField = value;
            }
        }

        /// <remarks/>
        public EntitiesList EntitiesList
        {
            get
            {
                return this.entitiesListField;
            }
            set
            {
                this.entitiesListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class Lessor
    {

        private Person personField;

        private Entity entityField;

        /// <remarks/>
        public Person Person
        {
            get
            {
                return this.personField;
            }
            set
            {
                this.personField = value;
            }
        }

        /// <remarks/>
        public Entity Entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class LeasingInfo
    {

        private string docNumberField;

        private System.DateTime docDateField;

        private bool docDateFieldSpecified;

        private System.DateTime endDateField;

        private bool endDateFieldSpecified;

        private string agreementField;

        private Lessor lessorField;

        /// <remarks/>
        public string DocNumber
        {
            get
            {
                return this.docNumberField;
            }
            set
            {
                this.docNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DocDate
        {
            get
            {
                return this.docDateField;
            }
            set
            {
                this.docDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocDateSpecified
        {
            get
            {
                return this.docDateFieldSpecified;
            }
            set
            {
                this.docDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified
        {
            get
            {
                return this.endDateFieldSpecified;
            }
            set
            {
                this.endDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Agreement
        {
            get
            {
                return this.agreementField;
            }
            set
            {
                this.agreementField = value;
            }
        }

        /// <remarks/>
        public Lessor Lessor
        {
            get
            {
                return this.lessorField;
            }
            set
            {
                this.lessorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class DeregistrationInfo
    {

        private System.DateTime deregistrationDateField;

        private bool deregistrationDateFieldSpecified;

        private string deregistrationReasonField;

        private string deregistrationDescriptionField;

        private string deregistrationCountryCodeField;

        private string deregistrationCountryNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DeregistrationDate
        {
            get
            {
                return this.deregistrationDateField;
            }
            set
            {
                this.deregistrationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeregistrationDateSpecified
        {
            get
            {
                return this.deregistrationDateFieldSpecified;
            }
            set
            {
                this.deregistrationDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string DeregistrationReason
        {
            get
            {
                return this.deregistrationReasonField;
            }
            set
            {
                this.deregistrationReasonField = value;
            }
        }

        /// <remarks/>
        public string DeregistrationDescription
        {
            get
            {
                return this.deregistrationDescriptionField;
            }
            set
            {
                this.deregistrationDescriptionField = value;
            }
        }

        /// <remarks/>
        public string DeregistrationCountryCode
        {
            get
            {
                return this.deregistrationCountryCodeField;
            }
            set
            {
                this.deregistrationCountryCodeField = value;
            }
        }

        /// <remarks/>
        public string DeregistrationCountryName
        {
            get
            {
                return this.deregistrationCountryNameField;
            }
            set
            {
                this.deregistrationCountryNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class RegistrationDocument
    {

        private string docNumberField;

        private System.DateTime docDateField;

        private bool docDateFieldSpecified;

        private string descriptionField;

        /// <remarks/>
        public string DocNumber
        {
            get
            {
                return this.docNumberField;
            }
            set
            {
                this.docNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DocDate
        {
            get
            {
                return this.docDateField;
            }
            set
            {
                this.docDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocDateSpecified
        {
            get
            {
                return this.docDateFieldSpecified;
            }
            set
            {
                this.docDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class RegistrationStatus
    {

        private bool isActiveRegistrationField;

        private bool isActiveRegistrationFieldSpecified;

        private int statusCodeField;

        private bool statusCodeFieldSpecified;

        private string statusNameField;

        /// <remarks/>
        public bool IsActiveRegistration
        {
            get
            {
                return this.isActiveRegistrationField;
            }
            set
            {
                this.isActiveRegistrationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsActiveRegistrationSpecified
        {
            get
            {
                return this.isActiveRegistrationFieldSpecified;
            }
            set
            {
                this.isActiveRegistrationFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusCodeSpecified
        {
            get
            {
                return this.statusCodeFieldSpecified;
            }
            set
            {
                this.statusCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string StatusName
        {
            get
            {
                return this.statusNameField;
            }
            set
            {
                this.statusNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class Registration
    {

        private int actNumberField;

        private bool actNumberFieldSpecified;

        private int registrationNumberField;

        private bool registrationNumberFieldSpecified;

        private System.DateTime registrationDateField;

        private bool registrationDateFieldSpecified;

        private string registrationMarkField;

        private bool isLastRegistrationField;

        private bool isLastRegistrationFieldSpecified;

        private RegistrationStatus registrationStatusField;

        private RegistrationDocument registrationDocumentField;

        private DeregistrationInfo deregistrationInfoField;

        private LeasingInfo leasingInfoField;

        private PersonEntitiesLists operatorsField;

        private PersonEntitiesLists ownersField;

        /// <remarks/>
        public int ActNumber
        {
            get
            {
                return this.actNumberField;
            }
            set
            {
                this.actNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActNumberSpecified
        {
            get
            {
                return this.actNumberFieldSpecified;
            }
            set
            {
                this.actNumberFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int RegistrationNumber
        {
            get
            {
                return this.registrationNumberField;
            }
            set
            {
                this.registrationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistrationNumberSpecified
        {
            get
            {
                return this.registrationNumberFieldSpecified;
            }
            set
            {
                this.registrationNumberFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistrationDateSpecified
        {
            get
            {
                return this.registrationDateFieldSpecified;
            }
            set
            {
                this.registrationDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string RegistrationMark
        {
            get
            {
                return this.registrationMarkField;
            }
            set
            {
                this.registrationMarkField = value;
            }
        }

        /// <remarks/>
        public bool IsLastRegistration
        {
            get
            {
                return this.isLastRegistrationField;
            }
            set
            {
                this.isLastRegistrationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsLastRegistrationSpecified
        {
            get
            {
                return this.isLastRegistrationFieldSpecified;
            }
            set
            {
                this.isLastRegistrationFieldSpecified = value;
            }
        }

        /// <remarks/>
        public RegistrationStatus RegistrationStatus
        {
            get
            {
                return this.registrationStatusField;
            }
            set
            {
                this.registrationStatusField = value;
            }
        }

        /// <remarks/>
        public RegistrationDocument RegistrationDocument
        {
            get
            {
                return this.registrationDocumentField;
            }
            set
            {
                this.registrationDocumentField = value;
            }
        }

        /// <remarks/>
        public DeregistrationInfo DeregistrationInfo
        {
            get
            {
                return this.deregistrationInfoField;
            }
            set
            {
                this.deregistrationInfoField = value;
            }
        }

        /// <remarks/>
        public LeasingInfo LeasingInfo
        {
            get
            {
                return this.leasingInfoField;
            }
            set
            {
                this.leasingInfoField = value;
            }
        }

        /// <remarks/>
        public PersonEntitiesLists Operators
        {
            get
            {
                return this.operatorsField;
            }
            set
            {
                this.operatorsField = value;
            }
        }

        /// <remarks/>
        public PersonEntitiesLists Owners
        {
            get
            {
                return this.ownersField;
            }
            set
            {
                this.ownersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class Registrations
    {

        private Registration[] registrationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registration")]
        public Registration[] Registration
        {
            get
            {
                return this.registrationField;
            }
            set
            {
                this.registrationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/GVA/AircraftsResponse")]
    public partial class AirCategory
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

}
