using System;
using System.Collections.Generic;
using System.Text;

namespace NRZ.RegiX.Client.ResponseModels
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse")]
    [System.Xml.Serialization.XmlRootAttribute("MotorVehicleRegistrationResponse", Namespace = "http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse", IsNullable = false)]
    public partial class MotorVehicleRegistrationResponse : BaseResponse
    {

        private ReturnInformation returnInformationField;

        private Vehicle[] vehiclesField;

        /// <remarks/>
        public ReturnInformation ReturnInformation
        {
            get
            {
                return this.returnInformationField;
            }
            set
            {
                this.returnInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Vehicle[] Vehicles
        {
            get
            {
                return this.vehiclesField;
            }
            set
            {
                this.vehiclesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse")]
    public partial class ReturnInformation
    {

        private string returnCodeField;

        private string infoField;

        /// <remarks/>
        public string ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }

        /// <remarks/>
        public string Info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse")]
    public partial class ForeignerPersonData
    {

        private string eGNField;

        private string lNChField;

        private string namesField;

        private string namesLatinField;

        private string genderNameField;

        private string genderNameLatinField;

        /// <remarks/>
        public string EGN
        {
            get
            {
                return this.eGNField;
            }
            set
            {
                this.eGNField = value;
            }
        }

        /// <remarks/>
        public string LNCh
        {
            get
            {
                return this.lNChField;
            }
            set
            {
                this.lNChField = value;
            }
        }

        /// <remarks/>
        public string Names
        {
            get
            {
                return this.namesField;
            }
            set
            {
                this.namesField = value;
            }
        }

        /// <remarks/>
        public string NamesLatin
        {
            get
            {
                return this.namesLatinField;
            }
            set
            {
                this.namesLatinField = value;
            }
        }

        /// <remarks/>
        public string GenderName
        {
            get
            {
                return this.genderNameField;
            }
            set
            {
                this.genderNameField = value;
            }
        }

        /// <remarks/>
        public string GenderNameLatin
        {
            get
            {
                return this.genderNameLatinField;
            }
            set
            {
                this.genderNameLatinField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse")]
    public partial class EntityData
    {

        private string identifierField;

        private string nameField;

        private string nameLatinField;

        /// <remarks/>
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string NameLatin
        {
            get
            {
                return this.nameLatinField;
            }
            set
            {
                this.nameLatinField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse")]
    public partial class PersonData
    {

        private string eGNField;

        private string firstNameField;

        private string surnameField;

        private string familyNameField;

        private string firstNameLatinField;

        private string surnameLatinField;

        private string lastNameLatinField;

        private System.DateTime birthDateField;

        private bool birthDateFieldSpecified;

        private string genderNameField;

        private string genderNameLatinField;

        /// <remarks/>
        public string EGN
        {
            get
            {
                return this.eGNField;
            }
            set
            {
                this.eGNField = value;
            }
        }

        /// <remarks/>
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        public string Surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }

        /// <remarks/>
        public string FamilyName
        {
            get
            {
                return this.familyNameField;
            }
            set
            {
                this.familyNameField = value;
            }
        }

        /// <remarks/>
        public string FirstNameLatin
        {
            get
            {
                return this.firstNameLatinField;
            }
            set
            {
                this.firstNameLatinField = value;
            }
        }

        /// <remarks/>
        public string SurnameLatin
        {
            get
            {
                return this.surnameLatinField;
            }
            set
            {
                this.surnameLatinField = value;
            }
        }

        /// <remarks/>
        public string LastNameLatin
        {
            get
            {
                return this.lastNameLatinField;
            }
            set
            {
                this.lastNameLatinField = value;
            }
        }

        /// <remarks/>
        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string GenderName
        {
            get
            {
                return this.genderNameField;
            }
            set
            {
                this.genderNameField = value;
            }
        }

        /// <remarks/>
        public string GenderNameLatin
        {
            get
            {
                return this.genderNameLatinField;
            }
            set
            {
                this.genderNameLatinField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse")]
    public partial class Vehicle
    {

        private string vehicleRegistrationNumberField;

        private System.DateTime firstRegistrationDateField;

        private bool firstRegistrationDateFieldSpecified;

        private string motorVehicleRegistrationCertificateNumberField;

        private PersonData ownerPersonDataField;

        private EntityData ownerEntityDataField;

        private ForeignerPersonData ownerForeignerPersonDataField;

        private string motorVehicleTypeField;

        private string motorVehicleTypeLatinField;

        private string motorVehicleModelField;

        private string motorVehicleModelLatinField;

        private string motorVehicleModelTypeField;

        private string tradeDescriptionField;

        private string tradeDescriptionLatinField;

        private string vINNumberField;

        private System.DateTime issueDateField;

        private bool issueDateFieldSpecified;

        private string categoryField;

        private string colorField;

        private string colorLatinField;

        private string engineNumberField;

        private string colorSecondaryField;

        private string colorSecondaryLatinField;

        /// <remarks/>
        public string VehicleRegistrationNumber
        {
            get
            {
                return this.vehicleRegistrationNumberField;
            }
            set
            {
                this.vehicleRegistrationNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime FirstRegistrationDate
        {
            get
            {
                return this.firstRegistrationDateField;
            }
            set
            {
                this.firstRegistrationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstRegistrationDateSpecified
        {
            get
            {
                return this.firstRegistrationDateFieldSpecified;
            }
            set
            {
                this.firstRegistrationDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string MotorVehicleRegistrationCertificateNumber
        {
            get
            {
                return this.motorVehicleRegistrationCertificateNumberField;
            }
            set
            {
                this.motorVehicleRegistrationCertificateNumberField = value;
            }
        }

        /// <remarks/>
        public PersonData OwnerPersonData
        {
            get
            {
                return this.ownerPersonDataField;
            }
            set
            {
                this.ownerPersonDataField = value;
            }
        }

        /// <remarks/>
        public EntityData OwnerEntityData
        {
            get
            {
                return this.ownerEntityDataField;
            }
            set
            {
                this.ownerEntityDataField = value;
            }
        }

        /// <remarks/>
        public ForeignerPersonData OwnerForeignerPersonData
        {
            get
            {
                return this.ownerForeignerPersonDataField;
            }
            set
            {
                this.ownerForeignerPersonDataField = value;
            }
        }

        /// <remarks/>
        public string MotorVehicleType
        {
            get
            {
                return this.motorVehicleTypeField;
            }
            set
            {
                this.motorVehicleTypeField = value;
            }
        }

        /// <remarks/>
        public string MotorVehicleTypeLatin
        {
            get
            {
                return this.motorVehicleTypeLatinField;
            }
            set
            {
                this.motorVehicleTypeLatinField = value;
            }
        }

        /// <remarks/>
        public string MotorVehicleModel
        {
            get
            {
                return this.motorVehicleModelField;
            }
            set
            {
                this.motorVehicleModelField = value;
            }
        }

        /// <remarks/>
        public string MotorVehicleModelLatin
        {
            get
            {
                return this.motorVehicleModelLatinField;
            }
            set
            {
                this.motorVehicleModelLatinField = value;
            }
        }

        /// <remarks/>
        public string MotorVehicleModelType
        {
            get
            {
                return this.motorVehicleModelTypeField;
            }
            set
            {
                this.motorVehicleModelTypeField = value;
            }
        }

        /// <remarks/>
        public string TradeDescription
        {
            get
            {
                return this.tradeDescriptionField;
            }
            set
            {
                this.tradeDescriptionField = value;
            }
        }

        /// <remarks/>
        public string TradeDescriptionLatin
        {
            get
            {
                return this.tradeDescriptionLatinField;
            }
            set
            {
                this.tradeDescriptionLatinField = value;
            }
        }

        /// <remarks/>
        public string VINNumber
        {
            get
            {
                return this.vINNumberField;
            }
            set
            {
                this.vINNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime IssueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueDateSpecified
        {
            get
            {
                return this.issueDateFieldSpecified;
            }
            set
            {
                this.issueDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        public string Color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }

        /// <remarks/>
        public string ColorLatin
        {
            get
            {
                return this.colorLatinField;
            }
            set
            {
                this.colorLatinField = value;
            }
        }

        /// <remarks/>
        public string EngineNumber
        {
            get
            {
                return this.engineNumberField;
            }
            set
            {
                this.engineNumberField = value;
            }
        }

        /// <remarks/>
        public string ColorSecondary
        {
            get
            {
                return this.colorSecondaryField;
            }
            set
            {
                this.colorSecondaryField = value;
            }
        }

        /// <remarks/>
        public string ColorSecondaryLatin
        {
            get
            {
                return this.colorSecondaryLatinField;
            }
            set
            {
                this.colorSecondaryLatinField = value;
            }
        }
    }

}
