using System;
using System.Collections.Generic;
using System.Text;

namespace NRZ.RegiX.Client.ResponseModels
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/IAMA/RegistrationInfoByOwnerResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://egov.bg/RegiX/IAMA/RegistrationInfoByOwnerResponse", IsNullable = false)]
    public partial class RegistrationInfoByOwnerResponse : BaseResponse
    {

        private VesselInfoType vesselInfoField;

        /// <remarks/>
        public VesselInfoType VesselInfo
        {
            get
            {
                return this.vesselInfoField;
            }
            set
            {
                this.vesselInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/IAMA")]
    public partial class VesselInfoType
    {

        private RegistrationDataType registrationDataField;

        private OwnerType[] ownersField;

        private MainPropertiesType mainFeaturesField;

        /// <remarks/>
        public RegistrationDataType RegistrationData
        {
            get
            {
                return this.registrationDataField;
            }
            set
            {
                this.registrationDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Owner", IsNullable = false)]
        public OwnerType[] Owners
        {
            get
            {
                return this.ownersField;
            }
            set
            {
                this.ownersField = value;
            }
        }

        /// <remarks/>
        public MainPropertiesType MainFeatures
        {
            get
            {
                return this.mainFeaturesField;
            }
            set
            {
                this.mainFeaturesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/IAMA")]
    public partial class RegistrationDataType
    {

        private string shipNameField;

        private string shipNameLatinField;

        private string registrationPortField;

        private string registrationNumberField;

        private string tomField;

        private string pageField;

        private string typeField;

        private StatusEnum statusField;

        private bool statusFieldSpecified;

        /// <remarks/>
        public string ShipName
        {
            get
            {
                return this.shipNameField;
            }
            set
            {
                this.shipNameField = value;
            }
        }

        /// <remarks/>
        public string ShipNameLatin
        {
            get
            {
                return this.shipNameLatinField;
            }
            set
            {
                this.shipNameLatinField = value;
            }
        }

        /// <remarks/>
        public string RegistrationPort
        {
            get
            {
                return this.registrationPortField;
            }
            set
            {
                this.registrationPortField = value;
            }
        }

        /// <remarks/>
        public string RegistrationNumber
        {
            get
            {
                return this.registrationNumberField;
            }
            set
            {
                this.registrationNumberField = value;
            }
        }

        /// <remarks/>
        public string Tom
        {
            get
            {
                return this.tomField;
            }
            set
            {
                this.tomField = value;
            }
        }

        /// <remarks/>
        public string Page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public StatusEnum Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/IAMA")]
    public enum StatusEnum
    {

        /// <remarks/>
        Active,

        /// <remarks/>
        Inactive,

        /// <remarks/>
        Erased,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/IAMA")]
    public partial class EngineType
    {

        private string systemModificationField;

        private string engineNumberField;

        private int powerField;

        private bool powerFieldSpecified;

        private string typeField;

        /// <remarks/>
        public string SystemModification
        {
            get
            {
                return this.systemModificationField;
            }
            set
            {
                this.systemModificationField = value;
            }
        }

        /// <remarks/>
        public string EngineNumber
        {
            get
            {
                return this.engineNumberField;
            }
            set
            {
                this.engineNumberField = value;
            }
        }

        /// <remarks/>
        public int Power
        {
            get
            {
                return this.powerField;
            }
            set
            {
                this.powerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PowerSpecified
        {
            get
            {
                return this.powerFieldSpecified;
            }
            set
            {
                this.powerFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/IAMA")]
    public partial class MainPropertiesType
    {

        private decimal btField;

        private bool btFieldSpecified;

        private decimal ntField;

        private bool ntFieldSpecified;

        private decimal maxLengthField;

        private bool maxLengthFieldSpecified;

        private decimal lengthBetweenPerpendicularsField;

        private bool lengthBetweenPerpendicularsFieldSpecified;

        private decimal maxWidthField;

        private bool maxWidthFieldSpecified;

        private decimal waterplaneField;

        private bool waterplaneFieldSpecified;

        private decimal shipboardHeightField;

        private bool shipboardHeightFieldSpecified;

        private decimal deadweightField;

        private bool deadweightFieldSpecified;

        private int numberOfEnginesField;

        private bool numberOfEnginesFieldSpecified;

        private string enginesFuelField;

        private double sumEnginePowerField;

        private bool sumEnginePowerFieldSpecified;

        private EngineType[] enginesField;

        private string bodyNumberField;

        /// <remarks/>
        public decimal BT
        {
            get
            {
                return this.btField;
            }
            set
            {
                this.btField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BTSpecified
        {
            get
            {
                return this.btFieldSpecified;
            }
            set
            {
                this.btFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal NT
        {
            get
            {
                return this.ntField;
            }
            set
            {
                this.ntField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NTSpecified
        {
            get
            {
                return this.ntFieldSpecified;
            }
            set
            {
                this.ntFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal MaxLength
        {
            get
            {
                return this.maxLengthField;
            }
            set
            {
                this.maxLengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxLengthSpecified
        {
            get
            {
                return this.maxLengthFieldSpecified;
            }
            set
            {
                this.maxLengthFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal LengthBetweenPerpendiculars
        {
            get
            {
                return this.lengthBetweenPerpendicularsField;
            }
            set
            {
                this.lengthBetweenPerpendicularsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LengthBetweenPerpendicularsSpecified
        {
            get
            {
                return this.lengthBetweenPerpendicularsFieldSpecified;
            }
            set
            {
                this.lengthBetweenPerpendicularsFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal MaxWidth
        {
            get
            {
                return this.maxWidthField;
            }
            set
            {
                this.maxWidthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxWidthSpecified
        {
            get
            {
                return this.maxWidthFieldSpecified;
            }
            set
            {
                this.maxWidthFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal Waterplane
        {
            get
            {
                return this.waterplaneField;
            }
            set
            {
                this.waterplaneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WaterplaneSpecified
        {
            get
            {
                return this.waterplaneFieldSpecified;
            }
            set
            {
                this.waterplaneFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal ShipboardHeight
        {
            get
            {
                return this.shipboardHeightField;
            }
            set
            {
                this.shipboardHeightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipboardHeightSpecified
        {
            get
            {
                return this.shipboardHeightFieldSpecified;
            }
            set
            {
                this.shipboardHeightFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal Deadweight
        {
            get
            {
                return this.deadweightField;
            }
            set
            {
                this.deadweightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeadweightSpecified
        {
            get
            {
                return this.deadweightFieldSpecified;
            }
            set
            {
                this.deadweightFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int NumberOfEngines
        {
            get
            {
                return this.numberOfEnginesField;
            }
            set
            {
                this.numberOfEnginesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfEnginesSpecified
        {
            get
            {
                return this.numberOfEnginesFieldSpecified;
            }
            set
            {
                this.numberOfEnginesFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string EnginesFuel
        {
            get
            {
                return this.enginesFuelField;
            }
            set
            {
                this.enginesFuelField = value;
            }
        }

        /// <remarks/>
        public double SumEnginePower
        {
            get
            {
                return this.sumEnginePowerField;
            }
            set
            {
                this.sumEnginePowerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SumEnginePowerSpecified
        {
            get
            {
                return this.sumEnginePowerFieldSpecified;
            }
            set
            {
                this.sumEnginePowerFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Engine", IsNullable = false)]
        public EngineType[] Engines
        {
            get
            {
                return this.enginesField;
            }
            set
            {
                this.enginesField = value;
            }
        }

        /// <remarks/>
        public string BodyNumber
        {
            get
            {
                return this.bodyNumberField;
            }
            set
            {
                this.bodyNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/IAMA")]
    public partial class PersonNames
    {

        private string firstNameField;

        private string surNameField;

        private string familyNameField;

        /// <remarks/>
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        public string SurName
        {
            get
            {
                return this.surNameField;
            }
            set
            {
                this.surNameField = value;
            }
        }

        /// <remarks/>
        public string FamilyName
        {
            get
            {
                return this.familyNameField;
            }
            set
            {
                this.familyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/IAMA")]
    public partial class PersonDataType
    {

        private PersonNames namesField;

        private string eGNField;

        /// <remarks/>
        public PersonNames Names
        {
            get
            {
                return this.namesField;
            }
            set
            {
                this.namesField = value;
            }
        }

        /// <remarks/>
        public string EGN
        {
            get
            {
                return this.eGNField;
            }
            set
            {
                this.eGNField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/IAMA")]
    public partial class CompanyDataType
    {

        private string companyNameField;

        private string eIKField;

        /// <remarks/>
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }

        /// <remarks/>
        public string EIK
        {
            get
            {
                return this.eIKField;
            }
            set
            {
                this.eIKField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/IAMA")]
    public partial class OwnerType
    {

        private bool isCompanyField;

        private bool isCompanyFieldSpecified;

        private CompanyDataType companyField;

        private PersonDataType personField;

        private string imoNumberField;

        private bool isUserField;

        private bool isUserFieldSpecified;

        private string addressField;

        /// <remarks/>
        public bool IsCompany
        {
            get
            {
                return this.isCompanyField;
            }
            set
            {
                this.isCompanyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsCompanySpecified
        {
            get
            {
                return this.isCompanyFieldSpecified;
            }
            set
            {
                this.isCompanyFieldSpecified = value;
            }
        }

        /// <remarks/>
        public CompanyDataType Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }

        /// <remarks/>
        public PersonDataType Person
        {
            get
            {
                return this.personField;
            }
            set
            {
                this.personField = value;
            }
        }

        /// <remarks/>
        public string ImoNumber
        {
            get
            {
                return this.imoNumberField;
            }
            set
            {
                this.imoNumberField = value;
            }
        }

        /// <remarks/>
        public bool IsUser
        {
            get
            {
                return this.isUserField;
            }
            set
            {
                this.isUserField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsUserSpecified
        {
            get
            {
                return this.isUserFieldSpecified;
            }
            set
            {
                this.isUserFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }



}
