
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace NRZ.RegiX.Client.ResponseModels
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute("TestStatusType", Namespace = "http://egov.bg/RegiX/AV/TR", IsNullable = false)]
    public enum StatusType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Нова партида")]
        Новапартида,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Пререгистрирана партида")]
        Пререгистриранапартида,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Нова закрита партида")]
        Новазакритапартида,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Пререгистрирана закрита партида")]
        Пререгистрираназакритапартида,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR/ValidUICResponse", TypeName = "ValidUICResponse")]
    [System.Xml.Serialization.XmlRootAttribute("ValidUICResponse", Namespace = "http://egov.bg/RegiX/AV/TR/ValidUICResponse", IsNullable = false)]
    public partial class ValidUICResponse : BaseResponse
    {

        private StatusType statusField;

        private bool statusFieldSpecified;

        private string uICField;

        private string companyField;

        private LegalFormType legalFormField;

        private System.DateTime dataValidForDateField;

        private bool dataValidForDateFieldSpecified;

        /// <remarks/>
        public StatusType Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string UIC
        {
            get
            {
                return this.uICField;
            }
            set
            {
                this.uICField = value;
            }
        }

        /// <remarks/>
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }

        /// <remarks/>
        public LegalFormType LegalForm
        {
            get
            {
                return this.legalFormField;
            }
            set
            {
                this.legalFormField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataValidForDate
        {
            get
            {
                return this.dataValidForDateField;
            }
            set
            {
                this.dataValidForDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataValidForDateSpecified
        {
            get
            {
                return this.dataValidForDateFieldSpecified;
            }
            set
            {
                this.dataValidForDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/AV/TR")]
    public partial class LegalFormType
    {

        private string legalFormAbbrField;

        private string legalFormNameField;

        /// <remarks/>
        public string LegalFormAbbr
        {
            get
            {
                return this.legalFormAbbrField;
            }
            set
            {
                this.legalFormAbbrField = value;
            }
        }

        /// <remarks/>
        public string LegalFormName
        {
            get
            {
                return this.legalFormNameField;
            }
            set
            {
                this.legalFormNameField = value;
            }
        }
    }


}

